### ISSUE TITLE
Minting 

### ISSUE THREAD

**Issue by OurMAVEN** [tokenocean/maven#1]
I went to mint tokens. 

The 1st time I was successful, but when I went to mint 10 tokens at once I received an error. 

I then went to mint 1 token and received an error.

There are funds in my wallet.

I used the same process all three times.

![20220412_101410](https://user-images.githubusercontent.com/103526396/163017688-15794f7a-b7dd-48cb-a7a7-08d71bd006a5.jpg)

![Screenshot_20220412-101147_Gallery](https://user-images.githubusercontent.com/103526396/163017391-05a9d317-6618-442f-83ab-eff37b1139b2.jpg)
![Screenshot_20220412-101218_Gallery](https://user-images.githubusercontent.com/103526396/163017397-687e56a5-d5c9-4dbe-b4d5-80d7d4cdffe4.jpg)

**Comment by secondl1ght** [comment]
Fixed
