### ISSUE TITLE
The word Artwork/Artist/Art to be replaced

### ISSUE THREAD

**Issue by OurMAVEN** [tokenocean/maven#14]
When the original meeting took place, it was asked that anywhere there was 'Art/Artwork/Artist/' mentioned these would be replaced with file/asset/seller.

We will add screen shots shortly.

**Comment by secondl1ght** [comment]
Are you still going to post the screenshots? That would be helpful and then I can make these updates for you!

**Comment by secondl1ght** [comment]
Received the screenshot and made the update, please re-open if you find anymore. Thanks
