### ISSUE TITLE
Important- How to use USDT Listing Function for Mortgage Payments

### ISSUE THREAD

**Issue by OurMAVEN** [tokenocean/maven#15]
MAVEN is going to be listing monthly payments for a mortgage.

With the volatility of the BTC market, MAVEN will be needing the use of the USDT that shows on the Listing page of a Token.

1. Other than choosing the actual USDT to list and adding the amount, what steps need to be taken by:

- The lister
- The purchaser

How will this show in their wallets?

**Comment by OurMAVEN** [comment]
Hello

This is not a feature request. This is already built into the LNFT platform.
This was to confirm how to use it and that this capability was operational.

**Comment by asoltys** [comment]
We tested this and it worked
