### ISSUE TITLE
Question on Transferring Asset out of MAVEN

### ISSUE THREAD

**Issue by OurMAVEN** [tokenocean/maven#18]
Patrick understood that NFTs could be transferred out to other Bitcoin/Liquid compatible wallets.

We are looking at how someone would transfer an Asset out of MAVEN to their own personal wallet of choice- ie Jade or another Bitcoin/Liquid friendly wallet.

Example, I went to transfer a token from our MAVEN account to my ES coinos.io wallet via Liquid, but the coinos address was not recognized by MAVEN to facilitate the transfer.

Can someone take us through this or is this function just not working outside of MAVEN wallets?

**Comment by secondl1ght** [comment]
This should work, maybe we could do a screen share sometime to confirm the steps?

**Comment by asoltys** [comment]
Which token were you trying to transfer? There's a caveat that tokens with royalties can only be transferred to multisig addresses that the platform maintains a signature on so that it can continue enforcing the royalty covenant.

**Comment by OurMAVEN** [comment]
I was just trying to transfer the MAVEN (rewards) token.  But if the owners of Las Perlas 117 Group LLC wanted to move their NFT to a hard Liquid wallet what steps would I need to do?  The sale was split into 3 different MAVEN wallets.
